export class ImageService {
  constructor(urlBase){
    'ngInject';
    this.urlBase = urlBase;
    this.imageType = [
      {
        type: 0,
        name: 'Grass 1',
        image: this.urlBase+'grass_1.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:true,
        isObject:false,
        imagePath: '',
      },
      {
        type: 1,
        name: 'Grass 2',
        image: this.urlBase+'grass_2.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:true,
        isObject:false,
        imagePath: '',
      },
      {
        type: 2,
        name: 'Grass 3',
        image: this.urlBase+'grass_3.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:true,
        isObject:false,
        imagePath: '',
      },
      {
        type: 3,
        name: 'Grass Flowers 1',
        image: this.urlBase+'grass_flowers_1.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:true,
        isObject:false,
        imagePath: '',
      },
      {
        type: 4,
        name: 'Ground 1',
        image: this.urlBase+'ground_1.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:true,
        isObject:false,
        imagePath: '',
      },
      {
        type: 5,
        name: 'Road 1',
        image: this.urlBase+'road_1.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:true,
        isObject:false,
        imagePath: '',
      },
      {
        type: 6,
        name: 'Road 2',
        image: this.urlBase+'road_2.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:true,
        isObject:false,
        imagePath: '',
      },
      {
        type: 7,
        name: 'Tall Grass 1',
        image: this.urlBase+'tall_grass_1.png',
        canPass: true,
        canHavePokemon:0.4,
        canHaveObject:false,
        isObject:false,
        imagePath: '',
      },
      {
        type: 8,
        name: 'Tall Grass 2',
        image: this.urlBase+'tall_grass_2.png',
        canPass: true,
        canHavePokemon:0.4,
        canHaveObject:false,
        isObject:false,
        imagePath: '',
      },
      {
        type: 9,
        name: 'Water 1',
        image: this.urlBase+'water_1.png',
        canPass: false,
        canHavePokemon:0.4,
        canHaveObject:false,
        isObject:false,
        imagePath: this.urlBase+'water_1/',
      },
      {
        type: 10,
        name: 'Water 2',
        image: this.urlBase+'water_2.png',
        canPass: false,
        canHavePokemon:0.4,
        canHaveObject:false,
        isObject:false,
        imagePath: '',
      },
      {
        type: 11,
        name: 'Wood Fance',
        image: this.urlBase+'wood_face_1.png',
        canPass: false,
        canHavePokemon:0,
        canHaveObject:false,
        isObject:true,
        imagePath: '',
      },
      {
        type: 12,
        name: 'Flowers 1',
        image: this.urlBase+'flower_1.png',
        canPass: true,
        canHavePokemon:0,
        canHaveObject:false,
        isObject:false,
        imagePath: '',
      },
      {
        type: 13,
        name: 'Tree 1',
        image: this.urlBase+'arvore_1.png',
        canPass: false,
        canHavePokemon:0,
        canHaveObject:false,
        isObject:true,
        imagePath: '',
      },
      {
        type: 14,
        name: 'Rock 1',
        image: this.urlBase+'rock_1.png',
        canPass: false,
        canHavePokemon:0,
        canHaveObject:false,
        isObject:true,
        imagePath: '',
      },
    ];
  }
}
